site_name: Assassins Creed

repo_name: "grupo10-assassinsCre"
repo_url: "https://github.com/SBD1/grupo10-assassinsCreed"

extra_css:
  - extra.css

theme:
  name: material
  language: "pt"
  logo: logo/logo.png
  palette:
    primary: "#fff"
    accent: "light blue"
  font:
    text: "Montserrat"
    code: "sans-serif"

nav:
  - Início: index.md
  - MER: MER/MER.md
  - Modelo Relacional: Modelo Relacional/Modelo Relacional.md
  - Normalização: Normalização/Normalização.md
  - SQL:
    - DDL: SQL/DDL/DDL.md
    - DML: SQL/DML/DML.md
  - Game: Game/Game.md


